// Generated by CoffeeScript 1.10.0
var manageCompetitors;

manageCompetitors = angular.module('manageCompetitors', []);

manageCompetitors.controller('compCtrl', function($scope, $http) {
  var makeCodes;
  $scope.newColor = {};
  $scope.comp = {};
  $scope.edit = [];
  $scope.tab = {};
  $scope.bgEdit = {};
  $scope.updPatternTxt = "Обновить";
  $scope.saveName = {};
  $scope.showTab = function(num) {
    var l, len, ref1, tab;
    $scope.tab.number = num;
    ref1 = $scope.tabs;
    for (l = 0, len = ref1.length; l < len; l++) {
      tab = ref1[l];
      tab["class"] = "";
    }
    $scope.tabs[num - 1]["class"] = "active";
  };

  /*
  Вкладки приложения
   */
  $scope.tabs = [
    {
      tab: 1,
      name: "Соискатели",
      "class": "active",
      id: "tab-1",
      file: "competitors.html",
      show: true
    }, {
      tab: 2,
      name: "Настройки",
      "class": "",
      id: "tab-2",
      file: "settings.html",
      show: false
    }, {
      tab: 3,
      name: "Об авторе",
      "class": "",
      id: "tab-3",
      file: "author.html",
      show: false
    }
  ];

  /*
  ======================== Действия с соискателями ===================================================
   */

  /*
  Загрузка соискателей
   */
  $http.get("http://applicants-tenet.rhcloud.com/api/1/dmitry5151/applicants").success(function(data) {
    $scope.competitors = data;
    makeCodes($scope.competitors);
  }).error(function(data, status, headers, config) {
    console.log(status);
  });

  /*
  Добавление соискателя
   */
  $scope.showAdd = function(visible) {
    $scope.comp.add = visible;
  };
  $scope.addCompetitor = function(formValid) {
    var user;
    if ($scope.newUserName !== void 0 && $scope.newUserName !== "" && $scope.newUserSurname !== void 0 && $scope.newUserSurname !== "") {
      user = {
        "name": $scope.newUserName,
        "surname": $scope.newUserSurname
      };
      $http.post("http://applicants-tenet.rhcloud.com/api/1/dmitry5151/applicants", user).success(function(uid) {
        user.id = uid.id;
        $scope.competitors.push(user);
        $scope.newUserName = "";
        $scope.newUserSurname = "";
        if (!$scope.multiUser) {
          $scope.comp.add = false;
        }
        makeCodes($scope.competitors);
      }).error(function(data, status, headers, config) {
        console.log(status);
        alert("Ошибка " + status + ". Данный соискатель уже имеется в базе.");
      });
    } else {
      alert("Поля заполнены некорректно!");
    }
    return false;
  };

  /*
  Редактирование соискателя
   */
  $scope.showEdit = function(visible, index, name, surname) {
    if (visible) {
      $scope.edit[index] = true;
      $scope.saveName = {
        "name": name,
        "surname": surname
      };
    } else {
      if ($scope.competitors[index].name !== void 0 && $scope.competitors[index].surname !== void 0) {
        $scope.competitors[index].name = $scope.saveName.name;
        $scope.competitors[index].surname = $scope.saveName.surname;
        $scope.edit[index] = false;
      }
    }
  };
  $scope.editUser = function(id, name, surname, index) {
    var user;
    console.log(name, surname);
    if (name !== void 0 && name !== "" && surname !== void 0 && surname !== "") {
      user = {
        "name": name,
        "surname": surname
      };
      $http.put("http://applicants-tenet.rhcloud.com/api/1/dmitry5151/applicants/" + id, user).success(function() {
        $scope.edit[index] = false;
      }).error(function(data, status, headers, config) {
        console.log(status);
        alert("Ошибка " + status + ". Данный соискатель уже имеется в базе.");
      });
    } else {
      alert("Имя или фамилия не соответствуют шаблону!");
    }
  };

  /*
  Удаление соискателя
   */
  $scope.deleteUser = function(name, surname, id, index) {
    var confirmDelete;
    confirmDelete = confirm("Удалить соискателя " + name + " " + surname + "?");
    if (confirmDelete) {
      $http["delete"]("http://applicants-tenet.rhcloud.com/api/1/dmitry5151/applicants/" + id).success(function() {
        $scope.competitors.splice(index, 1);
      }).error(function(data, status, headers, config) {
        console.log(status);
      });
    }
  };

  /*
  Удаление всех соискателей
   */
  $scope.deleteAllUsers = function() {
    var confirmDelete;
    confirmDelete = confirm("Удалить всех соискателей?");
    if (confirmDelete) {
      $http["delete"]("http://applicants-tenet.rhcloud.com/api/1/dmitry5151/applicants").success(function() {
        $scope.competitors = [];
      }).error(function(data, status, headers, config) {
        console.log(status);
      });
    }
  };

  /*
  Рассчитываем коды для пользователей
   */
  makeCodes = function(data) {
    var arr, g, i, j, k, key, l, len, len1, m, ref1, str, sum, sur, val;
    ref1 = $scope.competitors;
    for (key in ref1) {
      val = ref1[key];
      sum = 0;
      arr = [];
      sur = val.surname.toLowerCase();
      for (k = l = 0, len = sur.length; l < len; k = ++l) {
        j = sur[k];
        sum += j.charCodeAt(0);
        arr.push(j);
      }
      console.log(arr);
      arr.sort();
      str = "";
      for (i = m = 0, len1 = arr.length; m < len1; i = ++m) {
        g = arr[i];
        if (str.indexOf(g) < 0) {
          str += g;
        }
      }
      console.log(str);
      $scope.competitors[key].code = sum + str;
    }
  };

  /*
  ============================ Настройки приложения ============================
  Загрузка настроек
   */
  $http.get("http://applicants-tenet.rhcloud.com/api/1/dmitry5151/settings").success(function(data) {
    var a, key, ref, value;
    $scope.settings = data;
    if (!$scope.settings.bgColors) {
      $scope.bgColors = ["666", "999", "eee"];
    } else {
      $scope.bgColors = $scope.settings.bgColors;
    }
    ref = $scope.bgColors;
    a = [];
    for (key in ref) {
      value = ref[key];
      a.push(value);
    }
    $scope.bgColors = a;
    console.log($scope.bgColors);
  }).error(function(data, status, headers, config) {
    console.log(status);
  });

  /*
  Обновление паттерна
   */
  $scope.updatePattern = function(newpat) {
    var newPattern;
    newPattern = {
      "pattern": newpat
    };
    $http.put("http://applicants-tenet.rhcloud.com/api/1/dmitry5151/settings", newPattern).success(function(data) {
      console.log("Паттерн обновлен");
      $scope.updPatternTxt = "Паттерн сохранен";
    }).error(function(data, status, headers, config) {
      console.log(status);
      $scope.updPatternTxt = "Ошибка сохранения";
    });
  };
  $scope.updTxt = function() {
    return $scope.updPatternTxt = "Обновить";
  };
  $scope.setBgColor = function(bg) {
    bg = {
      "background": bg
    };
    return $http.put("http://applicants-tenet.rhcloud.com/api/1/dmitry5151/settings", bg).success(function(data) {
      $scope.settings.background = bg.background;
    }).error(function(data, status, headers, config) {
      console.log(status);
    });
  };

  /*
  Добавляем новый цвет в палитру
   */
  $scope.addBgColor = function() {
    var bgColors;
    console.log($scope.bgColors);
    if ($scope.newColor.value !== void 0) {
      $scope.bgColors.push($scope.newColor.value);
      $scope.newColor.value = "";
      bgColors = {
        "bgColors": $scope.bgColors
      };
      console.log(bgColors);
      $http.put("http://applicants-tenet.rhcloud.com/api/1/dmitry5151/settings", bgColors).success(function(data) {
        console.log("Цвета добавлены");
      }).error(function(data, status, headers, config) {
        console.log(status);
        $scope.updPatternTxt = "Ошибка сохранения";
      });
    }
  };

  /*
  Редактируем палитру (удаляем ненужные цвета)
   */
  $scope.editPalette = function(active, save) {
    var bgColors;
    if (save) {
      bgColors = {
        "bgColors": ""
      };
      $scope.settings.bgColors = $scope.bgColors;
      $http["delete"]("http://applicants-tenet.rhcloud.com/api/1/dmitry5151/settings").success(function(data) {
        $http.put("http://applicants-tenet.rhcloud.com/api/1/dmitry5151/settings", $scope.settings).success(function(data) {
          console.log("Цвета сохранены");
          $scope.bgEdit.active = active;
        }).error(function(data, status, headers, config) {
          console.log(status);
          $scope.updPatternTxt = "Ошибка сохранения";
        });
      }).error(function(data, status, headers, config) {
        console.log(status);
        $scope.updPatternTxt = "Ошибка сохранения";
      });
    } else {

    }
    $scope.bgEdit.active = active;
  };
  $scope.deleteColor = function(event, index, color) {
    console.log("index = " + index);
    $scope.bgColors.splice(index, 1);
    event.stopPropagation();
  };

  /*
  Сбрасываем все настройки
   */
  $scope.resetSettings = function() {
    var conf;
    conf = confirm("Сбросить все настройки?");
    if (conf) {
      $http["delete"]("http://applicants-tenet.rhcloud.com/api/1/dmitry5151/settings").success(function(data) {
        console.log("Настройки сброшены");
      }).error(function(data, status, headers, config) {
        console.log("Ошибка при сбросе настроек");
      });
    }
  };
});
