// Generated by CoffeeScript 1.10.0
var manageCompetitors;

manageCompetitors = angular.module('manageCompetitors', []);

manageCompetitors.controller('compCtrl', function($scope, $http) {
  $scope.work = "Приложение работает!";
  $scope.newColor = {};
  $scope.comp = {};
  $scope.edit = [];
  $scope.tab = {};
  $scope.bgEdit = {};
  $scope.updPatternTxt = "Обновить";
  $scope.showTab = function(num) {
    var i, len, ref, tab;
    $scope.tab.number = num;
    ref = $scope.tabs;
    for (i = 0, len = ref.length; i < len; i++) {
      tab = ref[i];
      tab["class"] = "";
    }
    $scope.tabs[num - 1]["class"] = "active";
  };

  /*
  Вкладки приложения
   */
  $scope.tabs = [
    {
      tab: 1,
      name: "Соискатели",
      "class": "active",
      id: "tab-1",
      file: "competitors.html",
      show: true
    }, {
      tab: 2,
      name: "Настройки",
      "class": "",
      id: "tab-2",
      file: "settings.html",
      show: false
    }, {
      tab: 3,
      name: "Об авторе",
      "class": "",
      id: "tab-3",
      file: "author.html",
      show: false
    }
  ];

  /*
  Загрузка соискателей
   */
  $http.get("http://applicants-tenet.rhcloud.com/api/1/dmitry5151/applicants").success(function(data) {
    $scope.competitors = data;
  }).error(function(data, status, headers, config) {
    console.log(status);
  });

  /*
  Удаление соискателя
   */
  $scope.deleteUser = function(name, surname, id, index) {
    var confirmDelete;
    confirmDelete = confirm("Удалить соискателя " + name + " " + surname + "?");
    if (confirmDelete) {
      $http["delete"]("http://applicants-tenet.rhcloud.com/api/1/dmitry5151/applicants/" + id).success(function() {
        $scope.competitors.splice(index, 1);
      }).error(function(data, status, headers, config) {
        console.log(status);
      });
    }
  };

  /*
  Редактирование соискателя
   */
  $scope.showEdit = function(visible, index) {
    if (visible) {
      $scope.edit[index] = true;
    } else {
      if ($scope.competitors[index].name !== void 0 && $scope.competitors[index].surname !== void 0) {
        $scope.edit[index] = false;
      }
    }
  };
  $scope.editUser = function(id, name, surname, index) {
    var user;
    if (name !== void 0 && surname !== void 0) {
      user = {
        "name": name,
        "surname": surname
      };
      $http.put("http://applicants-tenet.rhcloud.com/api/1/dmitry5151/applicants/" + id, user).success(function() {
        $scope.edit[index] = false;
      });
    }
  };

  /*
  Удаление всех соискателей
   */
  $scope.deleteAllUsers = function() {
    var confirmDelete;
    confirmDelete = confirm("Удалить всех соискателей?");
    if (confirmDelete) {
      $http["delete"]("http://applicants-tenet.rhcloud.com/api/1/dmitry5151/applicants").success(function() {
        $scope.competitors = [];
      }).error(function(data, status, headers, config) {
        console.log(status);
      });
    }
  };

  /*
  Добавление соискателя
   */
  $scope.showAdd = function(visible) {
    if (visible) {
      $scope.comp.add = true;
    } else {
      $scope.comp.add = false;
    }
  };
  $scope.addCompetitor = function() {
    var user;
    if ($scope.newUserName !== void 0 && $scope.newUserSurname !== void 0) {
      user = {
        "name": $scope.newUserName,
        "surname": $scope.newUserSurname
      };
      $http.post("http://applicants-tenet.rhcloud.com/api/1/dmitry5151/applicants", user).success(function(uid) {
        user.id = uid.id;
        $scope.competitors.push(user);
        $scope.newUserName = "";
        $scope.newUserSurname = "";
        $scope.comp.add = false;
      }).error(function(data, status, headers, config) {
        console.log(status);
      });
    }
    return false;
  };

  /*
  ============================ Настройки приложения ============================
  Загрузка настроек
   */
  $http.get("http://applicants-tenet.rhcloud.com/api/1/dmitry5151/settings").success(function(data) {
    $scope.settings = data;
    if (!$scope.settings.bgColors) {
      $scope.bgColors = ["666", "999", "eee"];
    } else {
      $scope.bgColors = $scope.settings.bgColors;
    }
  }).error(function(data, status, headers, config) {
    console.log(status);
  });

  /*
  Обновление паттерна
   */
  $scope.updatePattern = function(newpat) {
    var newPattern;
    newPattern = {
      "pattern": newpat
    };
    $http.put("http://applicants-tenet.rhcloud.com/api/1/dmitry5151/settings", newPattern).success(function(data) {
      console.log("Паттерн обновлен");
      $scope.updPatternTxt = "Паттерн сохранен";
    }).error(function(data, status, headers, config) {
      console.log(status);
      $scope.updPatternTxt = "Ошибка сохранения";
    });
  };
  $scope.updTxt = function() {
    return $scope.updPatternTxt = "Обновить";
  };
  $scope.setBgColor = function(bg) {
    bg = {
      "background": bg
    };
    return $http.put("http://applicants-tenet.rhcloud.com/api/1/dmitry5151/settings", bg).success(function(data) {
      $scope.settings.background = bg.background;
    }).error(function(data, status, headers, config) {
      console.log(status);
    });
  };

  /*
  Добавляем новый цвет в палитру
   */
  $scope.addBgColor = function() {
    var bgColors;
    console.log($scope.bgColors);
    if ($scope.newColor.value !== void 0) {
      $scope.bgColors.push($scope.newColor.value);
      $scope.newColor.value = "";
      bgColors = {
        "bgColors": $scope.bgColors
      };
      console.log(bgColors);
      $http.put("http://applicants-tenet.rhcloud.com/api/1/dmitry5151/settings", bgColors).success(function(data) {
        console.log("Цвета добавлены");
      }).error(function(data, status, headers, config) {
        console.log(status);
        $scope.updPatternTxt = "Ошибка сохранения";
      });
    }
  };

  /*
  Редактируем палитру (удаляем ненужные цвета)
   */
  $scope.editPalette = function(active) {
    $scope.bgEdit.active = active;
  };
  $scope.deleteColor = function(event, index, color) {
    var key, ref, value;
    console.log("index = " + index);
    ref = $scope.bgColors;
    for (key in ref) {
      value = ref[key];
      console.log(key, value);
    }
    event.stopPropagation();
  };

  /*
  Сбрасываем все настройки
   */
  $scope.resetSettings = function() {
    var conf;
    conf = confirm("Сбросить все настройки?");
    if (conf) {
      $http["delete"]("http://applicants-tenet.rhcloud.com/api/1/dmitry5151/settings").success(function(data) {
        console.log("Настройки сброшены");
      }).error(function(data, status, headers, config) {
        console.log("Ошибка при сбросе настроек");
      });
    }
  };
});
