// Generated by CoffeeScript 1.10.0
$(function() {
  var overlay, tabs;
  overlay = $('.overlay');
  $('.add').click(function(event) {
    event.stopPropagation();
  });
  overlay.click(function() {
    overlay.hide();
  });
  $('#show-form').click(function() {
    overlay.show();
  });
  $('#cansel').click(function() {
    overlay.hide();
  });

  /*
  Управление табами
   */
  tabs = $('.tab-container');
  tabs.each(function() {
    var a, active, firstTab, href, tab;
    a = $(this).find('ul.tabs a');
    tab = $(this).find('div.tabs-content>div');
    active = $(this).find('ul.tabs a.active').length;
    if (active === 0) {
      firstTab = $(this).find('ul.tabs li:first-child a');
      firstTab.attr({
        "class": 'active'
      });
      href = firstTab.attr("href");
      $("div#" + href).css({
        display: 'block'
      });
    }
    a.each(function() {
      $(this).on('click', function() {
        a.attr({
          "class": ''
        });
        tab.hide();
        $(this).attr({
          "class": 'active'
        });
        href = $(this).attr("href");
        $("div#" + href).css({
          display: 'block'
        });
        return false;
      });
    });
  });
});
