// Generated by CoffeeScript 1.10.0
$(function() {

  /*
  Всплытие/скрытие формы
   */
  var activateUser, ajax, bg, cells, competitor, curBg, deleteUser, getUser, overlay, responce, tabs, updateUser;
  overlay = $('.overlay');
  $('.add').click(function(event) {
    event.stopPropagation();
  });
  overlay.click(function() {
    overlay.hide();
  });
  $('#show-form').click(function() {
    overlay.show();
  });
  $('#cansel').click(function() {
    overlay.hide();
  });

  /*
  Управление табами
   */
  tabs = $('.tab-container');
  tabs.each(function() {
    var a, active, firstTab, href, tab;
    a = $(this).find('ul.tabs a');
    tab = $(this).find('div.tabs-content>div');
    active = $(this).find('ul.tabs a.active').length;
    if (active === 0) {
      firstTab = $(this).find('ul.tabs li:first-child a');
      firstTab.attr({
        "class": 'active'
      });
      href = firstTab.attr("href");
      $("div#" + href).css({
        display: 'block'
      });
    }
    a.each(function() {
      $(this).on('click', function() {
        a.attr({
          "class": ''
        });
        tab.hide();
        $(this).attr({
          "class": 'active'
        });
        href = $(this).attr("href");
        $("div#" + href).css({
          display: 'block'
        });
        return false;
      });
    });
  });

  /*
  Таблица соискателей - стили, управление строками
   */
  $('#competitors').on('change', function() {
    $('#competitors tr:even').css({
      background: '#ccc'
    });
  });

  /*
  Таблица настроек - цвета ячеек
   */
  bg = $('html');
  curBg = bg.css('background-color');
  cells = $('.color-settings td').not('.caption');
  $('#color1').css({
    'background-color': "#666"
  });
  $('#color2').css({
    'background-color': "#999"
  });
  $('#color3').css({
    'background-color': "#eee"
  });
  $('#color1').on('mouseover', function() {
    bg.css({
      'background-color': '#666'
    });
  }).on('mouseout', function() {
    bg.css({
      'background-color': curBg
    });
  }).on('click', function() {
    curBg = '#666';
    cells.text('');
    $(this).text("Текущий");
  });
  $('#color2').on('mouseover', function() {
    bg.css({
      'background-color': '#999'
    });
  }).on('mouseout', function() {
    bg.css({
      'background-color': curBg
    });
  }).on('click', function() {
    curBg = '#999';
    cells.text('');
    $(this).text("Текущий");
  });
  $('#color3').on('mouseover', function() {
    bg.css({
      'background-color': '#eee'
    });
  }).on('mouseout', function() {
    bg.css({
      'background-color': curBg
    });
  }).on('click', function() {
    curBg = '#eee';
    cells.text('');
    $(this).text("Текущий");
  });

  /*
  = Создаем запрос ===============================================================
   */
  competitor = {
    "id": "",
    "name": "Черт",
    "surname": "Лесной"
  };

  /*
  Ajax
   */
  ajax = function(uri, type, send) {
    $.ajax({
      crossDomain: true,
      url: "http://applicants-tenet.rhcloud.com/api/1/dmitry5151" + uri,
      type: type,
      data: send,
      success: function(data) {
        responce(data);
      }
    });
  };

  /*
  = Действия с пользователями ====================================================
   */
  getUser = function(id) {};
  deleteUser = function(id) {
    console.log("Удаление пользователя с id = " + id);
  };
  updateUser = function(id, name, surname) {
    return true;
  };
  activateUser = function() {
    $('.user-delete').on('click', function() {
      var uid;
      uid = $(this).parent().parent().find('.user-id').text();
      deleteUser(uid);
    });
    $('.user-edit').on('click', function() {
      var name, params, res, surname, uid, userEditStr;
      params = $(this).parent().parent();
      uid = params.find('.user-id').text();
      name = params.find('.user-name').text();
      surname = params.find('.user-surname').text();
      userEditStr = "";
      userEditStr = "<tr>\n    <td></td>\n    <td><input type=\"text\" value=\"" + name + "\" /></td>\n    <td><input type=\"text\" value=\"" + surname + "\" /></td>\n    <td><button class=\"save\" type=\"button\">Сохранить</button><button type=\"button\">Отмена</button></td>\n    <td></td>\n</tr>";
      params.after(userEditStr);
      params.hide();
      res = function() {
        $('.save').click(function() {
          return updateUser(uid, name, surname);
        });
      };
      console.log(res);
    });
  };

  /*
  Обработка ответа сервера
   */
  responce = function(data) {
    var i, j, len, user;
    user = "";
    for (j = 0, len = data.length; j < len; j++) {
      i = data[j];
      user += "<tr>\n    <td><img class=\"user-edit\" src=\"img/user-edit.png\" /></td>\n    <td class=\"user-name\">" + i.name + "</td>\n    <td class=\"user-surname\">" + i.surname + "</td>\n    <td class=\"user-id\">" + i.id + "</td>\n    <td><img class=\"user-delete\" src=\"img/user-delete.png\" /></td>\n</tr>";
    }
    $('#competitors').append(user);
    activateUser();
  };

  /*
  Инициализируем приложение
   */
  ajax('/applicants', 'GET', '');
});
